### ISSUE TITLE
Tidyselect sematic pickyness

### ISSUE THREAD

**Issue by thebioengineer** [GSK-Biostatistics/tfrmt#153]
Should we be picky at all about the tidy select semantics we allow in the col_plan. we currently support all tidyselect semantics, however, some really don't make sense to me to use in this scenario. For example `last_col()` grabs the last col, but what column that is depends on the order of the input data. `where()` accepts a function that returns "TRUE" or "FALSE" based on the evaluation of the column. Not sure we would want to support this semantic as part of col_plan. 

Thoughts?

**Comment by bzkrouse** [comment]
Piggybacking off of this, do we want to support tidyselect in other arguments, i.e. sorting_cols? 
We have tended to use tidyselect for specifications focused on the columns in the final table (i.e. col_plan, col_align_plan) and since sorting cols happen at the end should we treat them similarly? or should user be specific?

**Comment by statasaurus** [comment]
Because the order of the input columns matters we agree this shouldn't be allowed. Will need to be added
