### ISSUE TITLE
Formatting a column - table in long format

### ISSUE THREAD

**Issue by yannfeat** [GSK-Biostatistics/tfrmt#373]
Hi,

I have generated a mock table in long format:
![Rplot01](https://github.com/GSK-Biostatistics/tfrmt/assets/53322938/753ab846-2dff-4da7-ad7f-3a061579d239)

using the following dataframe:
```
df <- rbind(
  crossing(ord1 = c(1, 2),
           rowlbl2 = c("Placebo"),
           param = c("self"),
           column = c("n", "mean", "se", "ci")),
  crossing(ord1 = c(1, 2),
           rowlbl2 = c("Xan_Lo"),
           param = c("self", "comp_placebo"),
           column = c("n", "mean", "se", "ci")),
  crossing(ord1 = c(1, 2),
           rowlbl2 = c("Xan_Hi"),
           param = c("self", "comp_placebo", "comp_xan_lo"),
           column = c("n", "mean", "se", "ci"))
) %>%
  mutate(rowlbl1 = case_when(
    ord1 == 1 ~ "Subgroup level 1",
    ord1 == 2 ~ "Subgroup level 2"
  )) %>%
  mutate(rowlbl3 = case_when(
    param == "self" ~ "Model Estimates",
    param == "comp_placebo" ~ "Contrast / Placebo",
    param == "comp_xan_lo" ~ "Contrast / Xan_Lo"
  )) %>%
  mutate(ord2 = case_when(
    rowlbl2 == "Placebo" ~ 1,
    rowlbl2 == "Xan_Lo" ~ 2,
    rowlbl2 == "Xan_Hi" ~ 3
  )) %>%
  mutate(ord3 = case_when(
    param == "self" ~ 1,
    param == "comp_placebo" ~ 2,
    param == "comp_xan_lo" ~ 3
  )) %>%
  mutate(column = factor(column,
    levels = c("n", "mean", "se", "ci"),
    ordered = TRUE
  )) %>%
  arrange(ord1, ord2, ord3, column) %>%
  mutate(column = as.character(column))

> tail(df)
# A tibble: 6 x 8
   ord1 rowlbl2 param        column rowlbl1          rowlbl3            ord2  ord3
  <dbl> <chr>   <chr>        <ord>  <chr>            <chr>             <dbl> <dbl>
1     2 Xan_Hi  comp_placebo SE     Subgroup level 2 Contrast / Place~     3     2
2     2 Xan_Hi  comp_placebo 95% CI Subgroup level 2 Contrast / Place~     3     2
3     2 Xan_Hi  comp_xan_lo  n      Subgroup level 2 Contrast / Xan_Lo     3     3
4     2 Xan_Hi  comp_xan_lo  mean   Subgroup level 2 Contrast / Xan_Lo     3     3
5     2 Xan_Hi  comp_xan_lo  SE     Subgroup level 2 Contrast / Xan_Lo     3     3
6     2 Xan_Hi  comp_xan_lo  95% CI Subgroup level 2 Contrast / Xan_Lo     3     3
```

and these specifications:
```
tfrmt(
    group = vars(rowlbl1, rowlbl2),
    label = rowlbl3,
    param = param,
    column = column,
    sorting_cols = c(ord1, ord2, ord3),
    col_plan = col_plan(-starts_with("ord"))
)
```

The documentation clearly specifies how to apply a format to a row (param). Here, however, I would like to apply a format in a column-wise fashion (for example, set the number of significant digits for "n" to 0, and combine a lower bound and higher bound values into "95% CI"). I haven't understood how to do this, even after reading about `tfrmt_sigdig`. Could anybody help me?

**Comment by bzkrouse** [comment]
Hi, 
Thanks for reaching out and for the example!

You are correct that the documentation focuses on applying formats at a `param` level (and optionally adjusting the `group`/`label` values for finer control). This is because `param` is meant to reflect the value itself. It is also not tied to the final position in the table (this is dictated by the `group`, `label`, and `column` parameters). 

There are a couple of changes I'd recommend in your example:
	1. Create a `param` variable that aligns with the values to be formatted (param="n", etc), so you can format all of the n's, mean's, etc.  These can be as specific or as general as you need. 
	2. To make a confidence internal - First, your confidence limits will each need to appear as separate rows in the data. Again, have the `param` column reflect the value (e.g. "ci_lower" and "ci_upper"). To combine these in the formatting you will use `fmt_combine()`. 

There are a few examples in the vignettes to help you through. Take a look at https://gsk-biostatistics.github.io/tfrmt/articles/examples.html#ae-table which contains the `frmt_combine()` as well as a `param` and `column` variable that are very close but a bit different so you can see the purpose of each. 

Hope that helps! Please reach out if you have any other questions.
